<?php

/**
 * Class TrainingRecordModel
 *
 * @property integer id
 * @property integer block_id
 * @property integer page_id
 * @property string block_text_id
 * @property integer user_id
 * @property integer created_at
 * @property integer updated_at
 */
class TrainingRecordModel extends TrainingModel {

	protected static function getTable() {
		return 'training_records';
	}

	/**
	 * @param $id
	 *
	 * @return null|TrainingRecordModel
	 * @throws \Wikimedia\Rdbms\DBUnexpectedError
	 */
	public static function findById( $id ) {
		return parent::findById( $id );
	}

	/**
	 * @param null $condition
	 *
	 * @return null|TrainingRecordModel[]
	 */
	public static function findAll( $condition = null ) {
		return parent::findAll( $condition ); // TODO: Change the autogenerated stub
	}

	/**
	 * @param array $condition
	 *
	 * @return null|TrainingRecordModel
	 * @throws \Wikimedia\Rdbms\DBUnexpectedError
	 */
	public static function findBy( $condition ) {
		return parent::findBy( $condition ); // TODO: Change the autogenerated stub
	}


}
